config/routes.rb
Rails.application.routes.draw do
  get 'reservations/new'

  resources :restaurants, only: [:index, :show] do
    resources :reservations, only: [:new, :create]
  end
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :reservations
  has_many :tables, through: :reservations
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :table
  belongs_to :client
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :tables
  has_many :reservations, through: :tables
end

app/models/table.rb
class Table < ActiveRecord::Base
  belongs_to :restaurant
  has_many :reservations
  has_many :clients, through: :reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @reservation = Reservation.new
  end

  def create
    safe_reservation = params.require(:reservation).permit(:table_id, :client_id)
    reservation = Reservation.create(safe_reservation)
    redirect_to reservation.table.restaurant
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReservationStation</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reservations/new.html.erb
Reserve a table at <%= @restaurant.name %>
<%= form_for([@restaurant, @reservation]) do |f| %>
  <%= f.collection_select(:table_id, @restaurant.tables, :id, :id) %>
  <%= f.collection_select(:client_id, Client.all, :id, :name) %>
  <%= f.submit %>
<% end %>

app/views/restaurants/index.html.erb
<h1>All Restaurants</h1>
<ul>
  <% @restaurants.each do |restaurant| %>
    <li><%= link_to restaurant.name, restaurant %></li>
  <% end %>
</ul>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.name %></h2>
<%= link_to "Make a reservation", new_restaurant_reservation_path(@restaurant) %>
Current Reservations

<ul>
  <% @restaurant.reservations.each do |reservation| %>
    <li><%= reservation.client.name %></li>
  <% end %>
</ul>